<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/02/22 13:57:56
return array(

  // project
  'baseform' => '/www/otomasi_kantor/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => '/www/otomasi_kantor/apps/otomasi/lib/myUser.class.php',

  // modules
);
