# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      oracle://otrocana:otrocana12345@10.1.4.54/(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.1.4.54)(PORT=1521)))(CONNECT_DATA=(SID=SIMKARI)))
      #dsn:      mysql:host=localhost;dbname=otomasi_kantor
      #username: root
      #password: 
